import type { Metadata } from "next";
import { Josefin_Sans, Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", // improves performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${josefin.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-josefin">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}